version: "3.9"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      args:
        - ENVIRONMENT=dev
      dockerfile: dockerfiles/app/Dockerfile
    command: run_dev
    ports:
      - 5000:5000
    environment:
      - DATABASE_URI=postgresql+asyncpg://fastapi_template:fastapi_template@db/fastapi_template
      - DEBUG=True
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_template
      - POSTGRES_PASSWORD=fastapi_template
      - POSTGRES_DB=fastapi_template

volumes:
  postgres_data:
